### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

### ISSUE THREAD

**Issue by nofelmahmood** [minghao-wu/CRF-AE#3]
False
OrderedDict([('tag_scheme', 'iobes'), ('lower', True), ('zeros', False), ('char_dim', 25), ('char_lstm_dim', 25), ('char_bidirect', True), ('word_dim', 300), ('word_lstm_dim', 300), ('word_bidirect', True), ('all_emb', True), ('cap_dim', 0), ('crf', True), ('dropout', 0.5), ('reload', False), ('name', 'test'), ('char_mode', 'CNN'), ('train', 'dataset/eng.train'), ('dev', 'dataset/eng.testa'), ('test', 'dataset/eng.testb'), ('test_train', 'dataset/eng.train54019'), ('pre_emb', 'models/glove.6B.300d.txt'), ('use_gpu', False), ('features_dim', 196), ('feature_train', 'features/all_onehot.train'), ('feature_dev', 'features/all_onehot.testa'), ('feature_test', 'features/all_onehot.testb'), ('gazetter_dim', 3), ('gazetteer_train', 'features/gazetteer_PERLOC.train'), ('gazetteer_dev', 'features/gazetteer_PERLOC.testa'), ('gazetteer_test', 'features/gazetteer_PERLOC.testb'), ('pos_lambda', 1), ('wordshape_lambda', 1), ('gazetteer_lambda', 1), ('learning_rate', 0.015), ('epochs', 50)])
eval_script =  ./evaluation/conlleval.pl
eval_temp =  ./evaluation/temp
Found 7518 unique words (203621 in total)
Loading pretrained embeddings from models/glove.6B.300d.txt...
Found 85 unique characters
Found 19 unique named entity tags
14041 / 3250 / 3453 sentences in train / dev / test.
Loaded 400000 pretrained embeddings.
word_to_id:  400176
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:220: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_linear.weight, -bias, bias)
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:213: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_embedding, -bias, bias)
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:239: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:242: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:247: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
/Users/nofelmahmood/Documents/Master Thesis Topics/CRF-AE-master/utils.py:250: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
===========================================
Epoch 1 / 50
  0%|                                              | 0/14041 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 319, in <module>
    train_model(model, data, optimizer, step_lr_scheduler, num_epochs=parameters["epochs"])
  File "main.py", line 286, in train_model
    loss += neg_log_likelihood.data[0] / len(data['words'])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by mulangonando** [comment]
I also faced the same issue, Is there a solution or suggestions?

**Comment by minghao-wu** [comment]
I suggest you guys updating `neg_log_likelihood.data[0]` to `neg_log_likelihood.data.item()` in line 286

**Comment by nofelmahmood** [comment]
@minghao-wu Thanks it worked.
