### ISSUE TITLE
Where is mapping_file(models/mapping.pkl) used?

### ISSUE THREAD

**Issue by nofelmahmood** [minghao-wu/CRF-AE#5]
I am trying to understand how you map the glove word embeddings and create the vocabulary. In this regard, I have a question. Where is this mapping.pkl pickle dump used further in the codebase? I see no mention of it any further after you dump it to a file.

**Comment by minghao-wu** [comment]
Sorry for the late reply. Some code is missing and I don't remember all the details. However, basically, I built the vocabulary with train and dev set and removed those rare words.

**Comment by nofelmahmood** [comment]
No problem. Thanks for the reply.
